### ISSUE TITLE
【Flutter】依赖包 shared_preferences版本太久  pub get 报错

### ISSUE THREAD

**Issue by liuwei0514** [didi/DoraemonKit#795]
```
dependencies:
  sp_util: ^2.0.3
  streaming_shared_preferences: ^2.0.0
dev_dependencies:
  dokit: ^0.2.14
```

```
Because every version of dokit depends on shared_preferences ^0.5.12+4 and sp_util 2.0.3 depends on shared_preferences >=2.0.3 <4.0.0, dokit is incompatible with sp_util 2.0.3.
And because no versions of sp_util match >2.0.3 <3.0.0, dokit is incompatible with sp_util ^2.0.3.
So, because fanxiang depends on both sp_util ^2.0.3 and dokit ^0.2.14, version solving failed.
pub get failed (1; So, because fanxiang depends on both sp_util ^2.0.3 and dokit ^0.2.14, version solving failed.)
```
